<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\AddCustomerController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerLedgerController;
use App\Http\Controllers\AddMedicineController;
use App\Http\Controllers\MedicineListController;
use App\Http\Controllers\MedicineDetailsController;
use App\Http\Controllers\ManufacturerController;
use App\Http\Controllers\ManufacturerLedgerController;
use App\Http\Controllers\AddWastageReturnController;
use App\Http\Controllers\WastageReturnController;
use App\Http\Controllers\AddManufacturerReturnController;
use App\Http\Controllers\ManufacturerReturnController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\MembersProfileRegularController;
use App\Http\Controllers\AttendenceController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\IncomeListController;
use App\Http\Controllers\ExpenseListController;
use App\Http\Controllers\InvoiceListController;
use App\Http\Controllers\InvoiceDetailsController;
use App\Http\Controllers\SalesReportController;
use App\Http\Controllers\PurchaseReportController;
use App\Http\Controllers\StockReportController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\GeneralSettingsController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\IndexEcommerceController;
use App\Http\Controllers\IndexSalesController;
use App\Http\Controllers\IndexAnalyticsController;
use App\Http\Controllers\AppsInboxController;
use App\Http\Controllers\AppsMessagesController;
use App\Http\Controllers\AppsFileManagerController;
use App\Http\Controllers\AppsChatsController;
use App\Http\Controllers\AppsCalendarController;
use App\Http\Controllers\AppsKanbanController;
use App\Http\Controllers\ProjectCardController;
use App\Http\Controllers\ProjectListController;
use App\Http\Controllers\UserListRegularController;
use App\Http\Controllers\UserListCompactController;
use App\Http\Controllers\UserDetailsRegularController;
use App\Http\Controllers\UserProfileRegularController;
use App\Http\Controllers\UserCardController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\OrdersRegularController;
use App\Http\Controllers\OrdersSalesController;
use App\Http\Controllers\BlankController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\ComponentsController;
use App\Http\Controllers\EmailTemplatesController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;

Route::get('/index', [IndexController::class, 'showIndex'])->name('index');
Route::get('/user-profile', [UserProfileController::class, 'showUserProfile'])->name('user-profile');
Route::get('/add-customer', [AddCustomerController::class, 'showAddCustomer'])->name('add-customer');
Route::get('/customer', [CustomerController::class, 'showCustomer'])->name('customer');
Route::get('/customer-ledger', [CustomerLedgerController::class, 'showCustomerLedger'])->name('customer-ledger');
Route::get('/add-medicine', [AddMedicineController::class, 'showAddMedicine'])->name('add-medicine');
Route::get('/medicine-list', [MedicineListController::class, 'showMedicineList'])->name('medicine-list');
Route::get('/medicine-details', [MedicineDetailsController::class, 'showMedicineDetails'])->name('medicine-details');
Route::get('/manufacturer', [ManufacturerController::class, 'showManufacturer'])->name('manufacturer');
Route::get('/manufacturer-ledger', [ManufacturerLedgerController::class, 'showManufacturerLedger'])->name('manufacturer-ledger');
Route::get('/add-wastage-return', [AddWastageReturnController::class, 'showAddWastageReturn'])->name('add-wastage-return');
Route::get('/wastage-return', [WastageReturnController::class, 'showWastageReturn'])->name('wastage-return');
Route::get('/add-manufacturer-return', [AddManufacturerReturnController::class, 'showAddManufacturerReturn'])->name('add-manufacturer-return');
Route::get('/manufacturer-return', [ManufacturerReturnController::class, 'showManufacturerReturn'])->name('manufacturer-return');
Route::get('/member', [MemberController::class, 'showMember'])->name('member');
Route::get('/members-profile-regular', [MembersProfileRegularController::class, 'showMembersProfileRegular'])->name('members-profile-regular');
Route::get('/attendence', [AttendenceController::class, 'showAttendence'])->name('attendence');
Route::get('/salary', [SalaryController::class, 'showSalary'])->name('salary');
Route::get('/income-list', [IncomeListController::class, 'showIncomeList'])->name('income-list');
Route::get('/expense-list', [ExpenseListController::class, 'showExpenseList'])->name('expense-list');
Route::get('/invoice-list', [InvoiceListController::class, 'showInvoiceList'])->name('invoice-list');
Route::get('/invoice-details', [InvoiceDetailsController::class, 'showInvoiceDetails'])->name('invoice-details');
Route::get('/sales-report', [SalesReportController::class, 'showSalesReport'])->name('sales-report');
Route::get('/purchase-report', [PurchaseReportController::class, 'showPurchaseReport'])->name('purchase-report');
Route::get('/stock-report', [StockReportController::class, 'showStockReport'])->name('stock-report');
Route::get('/support', [SupportController::class, 'showSupport'])->name('support');
Route::get('/general-settings', [GeneralSettingsController::class, 'showGeneralSettings'])->name('general-settings');
Route::get('/hospital/index', [HospitalController::class, 'showHospitalIndex'])->name('hospital/index');
Route::get('/hospital/appointment', [HospitalController::class, 'showHospitalAppointment'])->name('hospital/appointment');
Route::get('/hospital/patient-add', [HospitalController::class, 'showHospitalPatientAdd'])->name('hospital/patient-add');
Route::get('/hospital/patient-list', [HospitalController::class, 'showHospitalPatientList'])->name('hospital/patient-list');
Route::get('/hospital/patient-profile', [HospitalController::class, 'showHospitalPatientProfile'])->name('hospital/patient-profile');
Route::get('/hospital/doctor-nurse-add', [HospitalController::class, 'showHospitalDoctorNurseAdd'])->name('hospital/doctor-nurse-add');
Route::get('/hospital/doctor-nurse-list', [HospitalController::class, 'showHospitalDoctorNurseList'])->name('hospital/doctor-nurse-list');
Route::get('/hospital/income-list', [HospitalController::class, 'showHospitalIncomeList'])->name('hospital/income-list');
Route::get('/hospital/expense-list', [HospitalController::class, 'showHospitalExpenseList'])->name('hospital/expense-list');
Route::get('/hospital/invoice-list', [HospitalController::class, 'showHospitalInvoiceList'])->name('hospital/invoice-list');
Route::get('/hospital/invoice-details', [HospitalController::class, 'showHospitalInvoiceDetails'])->name('hospital/invoice-details');
Route::get('/hospital/birth-report', [HospitalController::class, 'showHospitalBirthReport'])->name('hospital/birth-report');
Route::get('/hospital/blood-bank', [HospitalController::class, 'showHospitalBloodBank'])->name('hospital/blood-bank');
Route::get('/hospital/inventory-items', [HospitalController::class, 'showHospitalInventoryItems'])->name('hospital/inventory-items');
Route::get('/hospital/bed-group', [HospitalController::class, 'showHospitalBedGroup'])->name('hospital/bed-group');
Route::get('/hospital/bed-allotment', [HospitalController::class, 'showHospitalBedAllotment'])->name('hospital/bed-allotment');
Route::get('/hospital/department', [HospitalController::class, 'showHospitalDepartment'])->name('hospital/department');
Route::get('/hospital/death-report', [HospitalController::class, 'showHospitalDeathReport'])->name('hospital/death-report');
Route::get('/hospital/user-profile', [HospitalController::class, 'showHospitalUserProfile'])->name('hospital/user-profile');
Route::get('/hospital/settings', [HospitalController::class, 'showHospitalSettings'])->name('hospital/settings');
Route::get('/index-ecommerce', [IndexEcommerceController::class, 'showIndexEcommerce'])->name('index-ecommerce');
Route::get('/index-sales', [IndexSalesController::class, 'showIndexSales'])->name('index-sales');
Route::get('/index-analytics', [IndexAnalyticsController::class, 'showIndexAnalytics'])->name('index-analytics');
Route::get('/apps-inbox', [AppsInboxController::class, 'showAppsInbox'])->name('apps-inbox');
Route::get('/apps-messages', [AppsMessagesController::class, 'showAppsMessages'])->name('apps-messages');
Route::get('/apps-file-manager', [AppsFileManagerController::class, 'showAppsFileManager'])->name('apps-file-manager');
Route::get('/apps-chats', [AppsChatsController::class, 'showAppsChats'])->name('apps-chats');
Route::get('/apps-calendar', [AppsCalendarController::class, 'showAppsCalendar'])->name('apps-calendar');
Route::get('/apps-kanban', [AppsKanbanController::class, 'showAppsKanban'])->name('apps-kanban');
Route::get('/project-card', [ProjectCardController::class, 'showProjectCard'])->name('project-card');
Route::get('/project-list', [ProjectListController::class, 'showProjectList'])->name('project-list');
Route::get('/user-list-regular', [UserListRegularController::class, 'showUserListRegular'])->name('user-list-regular');
Route::get('/user-list-compact', [UserListCompactController::class, 'showUserListCompact'])->name('user-list-compact');
Route::get('/user-details-regular', [UserDetailsRegularController::class, 'showUserDetailsRegular'])->name('user-details-regular');
Route::get('/user-profile-regular', [UserProfileRegularController::class, 'showUserProfileRegular'])->name('user-profile-regular');
Route::get('/user-card', [UserCardController::class, 'showUserCard'])->name('user-card');
Route::get('/products', [ProductsController::class, 'showProducts'])->name('products');
Route::get('/orders-regular', [OrdersRegularController::class, 'showOrdersRegular'])->name('orders-regular');
Route::get('/orders-sales', [OrdersSalesController::class, 'showOrdersSales'])->name('orders-sales');
Route::get('/_blank', [BlankController::class, 'showBlank'])->name('_blank');
Route::get('/pages/faqs', [PagesController::class, 'showPagesFaqs'])->name('pages/faqs');
Route::get('/pages/terms-policy', [PagesController::class, 'showPagesTermsPolicy'])->name('pages/terms-policy');
Route::get('/pages/regular-v1', [PagesController::class, 'showPagesRegularV1'])->name('pages/regular-v1');
Route::get('/pages/regular-v2', [PagesController::class, 'showPagesRegularV2'])->name('pages/regular-v2');
Route::get('/pages/auths/auth-login', [PagesController::class, 'showPagesAuthsAuthLogin'])->name('pages/auths/auth-login');
Route::get('/pages/auths/auth-register', [PagesController::class, 'showPagesAuthsAuthRegister'])->name('pages/auths/auth-register');
Route::get('/pages/auths/auth-reset', [PagesController::class, 'showPagesAuthsAuthReset'])->name('pages/auths/auth-reset');
Route::get('/pages/auths/auth-success', [PagesController::class, 'showPagesAuthsAuthSuccess'])->name('pages/auths/auth-success');
Route::get('/pages/auths/auth-login-v2', [PagesController::class, 'showPagesAuthsAuthLoginV2'])->name('pages/auths/auth-login-v2');
Route::get('/pages/auths/auth-register-v2', [PagesController::class, 'showPagesAuthsAuthRegisterV2'])->name('pages/auths/auth-register-v2');
Route::get('/pages/auths/auth-reset-v2', [PagesController::class, 'showPagesAuthsAuthResetV2'])->name('pages/auths/auth-reset-v2');
Route::get('/pages/auths/auth-success-v2', [PagesController::class, 'showPagesAuthsAuthSuccessV2'])->name('pages/auths/auth-success-v2');
Route::get('/pages/auths/auth-login-v3', [PagesController::class, 'showPagesAuthsAuthLoginV3'])->name('pages/auths/auth-login-v3');
Route::get('/pages/auths/auth-register-v3', [PagesController::class, 'showPagesAuthsAuthRegisterV3'])->name('pages/auths/auth-register-v3');
Route::get('/pages/auths/auth-reset-v3', [PagesController::class, 'showPagesAuthsAuthResetV3'])->name('pages/auths/auth-reset-v3');
Route::get('/pages/auths/auth-success-v3', [PagesController::class, 'showPagesAuthsAuthSuccessV3'])->name('pages/auths/auth-success-v3');
Route::get('/pages/errors/404-classic', [PagesController::class, 'showPagesErrors404Classic'])->name('pages/errors/404-classic');
Route::get('/pages/errors/504-classic', [PagesController::class, 'showPagesErrors504Classic'])->name('pages/errors/504-classic');
Route::get('/pages/errors/404-s1', [PagesController::class, 'showPagesErrors404S1'])->name('pages/errors/404-s1');
Route::get('/pages/errors/504-s1', [PagesController::class, 'showPagesErrors504S1'])->name('pages/errors/504-s1');
Route::get('/components', [ComponentsController::class, 'showComponents'])->name('components');
Route::get('/components/elements/alerts', [ComponentsController::class, 'showComponentsElementsAlerts'])->name('components/elements/alerts');
Route::get('/components/elements/accordions', [ComponentsController::class, 'showComponentsElementsAccordions'])->name('components/elements/accordions');
Route::get('/components/elements/avatar', [ComponentsController::class, 'showComponentsElementsAvatar'])->name('components/elements/avatar');
Route::get('/components/elements/badges', [ComponentsController::class, 'showComponentsElementsBadges'])->name('components/elements/badges');
Route::get('/components/elements/buttons', [ComponentsController::class, 'showComponentsElementsButtons'])->name('components/elements/buttons');
Route::get('/components/elements/buttons-group', [ComponentsController::class, 'showComponentsElementsButtonsGroup'])->name('components/elements/buttons-group');
Route::get('/components/elements/breadcrumb', [ComponentsController::class, 'showComponentsElementsBreadcrumb'])->name('components/elements/breadcrumb');
Route::get('/components/elements/cards', [ComponentsController::class, 'showComponentsElementsCards'])->name('components/elements/cards');
Route::get('/components/elements/carousel', [ComponentsController::class, 'showComponentsElementsCarousel'])->name('components/elements/carousel');
Route::get('/components/elements/list-dropdown', [ComponentsController::class, 'showComponentsElementsListDropdown'])->name('components/elements/list-dropdown');
Route::get('/components/elements/modals', [ComponentsController::class, 'showComponentsElementsModals'])->name('components/elements/modals');
Route::get('/components/elements/pagination', [ComponentsController::class, 'showComponentsElementsPagination'])->name('components/elements/pagination');
Route::get('/components/elements/popover', [ComponentsController::class, 'showComponentsElementsPopover'])->name('components/elements/popover');
Route::get('/components/elements/progress', [ComponentsController::class, 'showComponentsElementsProgress'])->name('components/elements/progress');
Route::get('/components/elements/spinner', [ComponentsController::class, 'showComponentsElementsSpinner'])->name('components/elements/spinner');
Route::get('/components/elements/tabs', [ComponentsController::class, 'showComponentsElementsTabs'])->name('components/elements/tabs');
Route::get('/components/elements/toast', [ComponentsController::class, 'showComponentsElementsToast'])->name('components/elements/toast');
Route::get('/components/elements/tooltip', [ComponentsController::class, 'showComponentsElementsTooltip'])->name('components/elements/tooltip');
Route::get('/components/elements/typography', [ComponentsController::class, 'showComponentsElementsTypography'])->name('components/elements/typography');
Route::get('/components/elements/util-border', [ComponentsController::class, 'showComponentsElementsUtilBorder'])->name('components/elements/util-border');
Route::get('/components/elements/util-colors', [ComponentsController::class, 'showComponentsElementsUtilColors'])->name('components/elements/util-colors');
Route::get('/components/elements/util-display', [ComponentsController::class, 'showComponentsElementsUtilDisplay'])->name('components/elements/util-display');
Route::get('/components/elements/util-embeded', [ComponentsController::class, 'showComponentsElementsUtilEmbeded'])->name('components/elements/util-embeded');
Route::get('/components/elements/util-flex', [ComponentsController::class, 'showComponentsElementsUtilFlex'])->name('components/elements/util-flex');
Route::get('/components/elements/util-text', [ComponentsController::class, 'showComponentsElementsUtilText'])->name('components/elements/util-text');
Route::get('/components/elements/util-sizing', [ComponentsController::class, 'showComponentsElementsUtilSizing'])->name('components/elements/util-sizing');
Route::get('/components/elements/util-spacing', [ComponentsController::class, 'showComponentsElementsUtilSpacing'])->name('components/elements/util-spacing');
Route::get('/components/elements/util-others', [ComponentsController::class, 'showComponentsElementsUtilOthers'])->name('components/elements/util-others');
Route::get('/components/misc/svg-icons', [ComponentsController::class, 'showComponentsMiscSvgIcons'])->name('components/misc/svg-icons');
Route::get('/components/misc/nioicon', [ComponentsController::class, 'showComponentsMiscNioicon'])->name('components/misc/nioicon');
Route::get('/components/misc/icons', [ComponentsController::class, 'showComponentsMiscIcons'])->name('components/misc/icons');
Route::get('/components/tables/table-basic', [ComponentsController::class, 'showComponentsTablesTableBasic'])->name('components/tables/table-basic');
Route::get('/components/tables/table-special', [ComponentsController::class, 'showComponentsTablesTableSpecial'])->name('components/tables/table-special');
Route::get('/components/tables/table-datatable', [ComponentsController::class, 'showComponentsTablesTableDatatable'])->name('components/tables/table-datatable');
Route::get('/components/forms/form-elements', [ComponentsController::class, 'showComponentsFormsFormElements'])->name('components/forms/form-elements');
Route::get('/components/forms/form-upload', [ComponentsController::class, 'showComponentsFormsFormUpload'])->name('components/forms/form-upload');
Route::get('/components/forms/datetime-picker', [ComponentsController::class, 'showComponentsFormsDatetimePicker'])->name('components/forms/datetime-picker');
Route::get('/components/forms/number-spinner', [ComponentsController::class, 'showComponentsFormsNumberSpinner'])->name('components/forms/number-spinner');
Route::get('/components/forms/form-layouts', [ComponentsController::class, 'showComponentsFormsFormLayouts'])->name('components/forms/form-layouts');
Route::get('/components/forms/form-validation', [ComponentsController::class, 'showComponentsFormsFormValidation'])->name('components/forms/form-validation');
Route::get('/components/forms/form-wizard', [ComponentsController::class, 'showComponentsFormsFormWizard'])->name('components/forms/form-wizard');
Route::get('/components/forms/form-summernote', [ComponentsController::class, 'showComponentsFormsFormSummernote'])->name('components/forms/form-summernote');
Route::get('/components/forms/form-quill', [ComponentsController::class, 'showComponentsFormsFormQuill'])->name('components/forms/form-quill');
Route::get('/components/forms/form-tinymce', [ComponentsController::class, 'showComponentsFormsFormTinymce'])->name('components/forms/form-tinymce');
Route::get('/components/charts/chartjs', [ComponentsController::class, 'showComponentsChartsChartjs'])->name('components/charts/chartjs');
Route::get('/components/charts/knob', [ComponentsController::class, 'showComponentsChartsKnob'])->name('components/charts/knob');
Route::get('/components/misc/toastr', [ComponentsController::class, 'showComponentsMiscToastr'])->name('components/misc/toastr');
Route::get('/components/misc/sweet-alert', [ComponentsController::class, 'showComponentsMiscSweetAlert'])->name('components/misc/sweet-alert');
Route::get('/components/misc/js-tree', [ComponentsController::class, 'showComponentsMiscJsTree'])->name('components/misc/js-tree');
Route::get('/components/misc/dual-listbox', [ComponentsController::class, 'showComponentsMiscDualListbox'])->name('components/misc/dual-listbox');
Route::get('/email-templates', [EmailTemplatesController::class, 'showEmailTemplates'])->name('email-templates');
Route::get('/hospital/settings-account-log', [HospitalController::class, 'showHospitalSettingsAccountLog'])->name('hospital/settings-account-log');
Route::get('/hospital/invoice-print', [HospitalController::class, 'showHospitalInvoicePrint'])->name('hospital/invoice-print');
Route::get('/hospital/settings-member', [HospitalController::class, 'showHospitalSettingsMember'])->name('hospital/settings-member');
Route::get('/hospital/settings-email', [HospitalController::class, 'showHospitalSettingsEmail'])->name('hospital/settings-email');
Route::get('/hospital/settings-security', [HospitalController::class, 'showHospitalSettingsSecurity'])->name('hospital/settings-security');
Route::get('/login', [LoginController::class, 'showLogin'])->name('login');
Route::get('/register', [RegisterController::class, 'showRegister'])->name('register');
